### ISSUE TITLE
Unnecessary ruby errors in check output 

### ISSUE THREAD

**Issue by jaykumar-jnpr** [sensu-plugins/sensu-plugins-filesystem-checks#14]
Unnecessary ruby errors in check output, need to sanitize it

/opt/sensu/embedded/bin/check-fs-writable.rb --dir '/b' 

```
Check failed to run: No space left on device, ["/opt/sensu/embedded/lib/ruby/2.3.0/delegate.rb:341:in `read'", "/opt/sensu/embedded/lib/ruby/2.3.0/delegate.rb:341:in `block in delegating_block'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-filesystem-checks-0.2.0/bin/check-fs-writable.rb:142:in `block in manual_test'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-filesystem-checks-0.2.0/bin/check-fs-writable.rb:135:in `each'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-filesystem-checks-0.2.0/bin/check-fs-writable.rb:135:in `manual_test'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-filesystem-checks-0.2.0/bin/check-fs-writable.rb:151:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.3.0/lib/sensu-plugin/cli.rb:57:in `block in <class:CLI>'"]
```

My workaround was (not elegant),

```
/opt/sensu/embedded/bin/check-fs-writable.rb --dir '/b' | awk -F , '{print $1}' ; exit ${PIPESTATUS[0]}
```

**Comment by Savemech** [comment]
this is very nice, any chances to get this embedded?

**Comment by majormoses** [comment]
ideally we could rescue (ideally on some condition) without looking at the code though I am not sure the feasibility of this.
